/* Chapter 1 quiz. Each question: q, options (4), answer (0-3), explain, section (textbook anchor id). */
window.QUIZ = {
  chapter: "ch1",
  title: "Chapter 1: Common Stock",
  textbook: "textbook.html",
  questions: [
    { q: "A corporation is liquidated. Which group is paid last?",
      options: ["Debenture holders", "Preferred stockholders", "Common stockholders", "General creditors"], answer: 2,
      explain: "Common stockholders hold the residual claim and are paid only after all creditors and preferred stockholders.",
      section: "s1-2-liquidation" },
    { q: "A company has 5,000,000 shares authorized, 3,000,000 issued, and 400,000 in treasury. How many shares are outstanding?",
      options: ["5,000,000", "3,400,000", "2,600,000", "2,000,000"], answer: 2,
      explain: "Outstanding = issued − treasury = 3,000,000 − 400,000 = 2,600,000. Authorized shares do not enter the calculation.",
      section: "s1-3-share-counts" },
    { q: "Which value of common stock is set arbitrarily at issuance for accounting purposes?",
      options: ["Par value", "Market value", "Book value", "Liquidation value"], answer: 0,
      explain: "Par value is an arbitrary bookkeeping figure. For common stock it has no relationship to market price.",
      section: "s1-3-value" },
    { q: "An investor owns 200 shares. Four directors are up for election under cumulative voting. What is the most votes the investor can cast for a single candidate?",
      options: ["200", "400", "800", "50"], answer: 2,
      explain: "Cumulative voting: 200 shares × 4 seats = 800 votes, which can all go to one candidate. Under statutory voting the maximum would be 200.",
      section: "s1-2-voting" },
    { q: "Cumulative voting primarily benefits:",
      options: ["The board of directors", "Majority shareholders", "Bondholders", "Minority shareholders"], answer: 3,
      explain: "By stacking votes on one candidate, smaller holders have a better chance of electing at least one director.",
      section: "s1-2-voting" },
    { q: "Common stockholders generally vote on all of the following EXCEPT:",
      options: ["Electing the board of directors", "A 3-for-1 stock split", "A proposed merger", "The amount of a cash dividend"], answer: 3,
      explain: "The board of directors declares dividends and sets the amount. Shareholders do not vote on them.",
      section: "s1-2-voting" },
    { q: "The main purpose of a preemptive right is to let existing shareholders:",
      options: ["Receive dividends before preferred holders", "Maintain their proportionate ownership", "Sell shares back to the company at par", "Vote twice on board seats"], answer: 1,
      explain: "Preemptive rights let holders buy new shares before the public, so their percentage ownership is not diluted.",
      section: "s1-2-preemptive" },
    { q: "Treasury stock:",
      options: ["Neither votes nor receives dividends", "Votes and receives dividends", "Votes but receives no dividends", "Is counted as outstanding"], answer: 0,
      explain: "Repurchased shares held by the company have no voting rights and receive no dividends. They are issued but not outstanding.",
      section: "s1-3-share-counts" },
    { q: "Which of these dates is NOT set by the board of directors?",
      options: ["Declaration date", "Ex-dividend date", "Record date", "Payable date"], answer: 1,
      explain: "The exchange (or FINRA for OTC stocks) sets the ex-dividend date based on the record date and settlement rules.",
      section: "s1-2-dividend-dates" },
    { q: "Under regular-way T+1 settlement, a company sets a Thursday record date. The ex-dividend date is:",
      options: ["The Tuesday before", "The Wednesday before", "The same Thursday", "The following Friday"], answer: 2,
      explain: "With T+1 settlement, the ex-date is the same day as the record date. A trade on Wednesday settles Thursday and gets the dividend; a Thursday trade settles Friday and does not.",
      section: "s1-2-dividend-dates" },
    { q: "An investor buys a stock on its ex-dividend date. Who receives the upcoming dividend?",
      options: ["The buyer", "The seller", "It is split between them", "Neither; it is forfeited"], answer: 1,
      explain: "Buyers on or after the ex-date are not entitled. The seller is still the holder of record and receives the dividend.",
      section: "s1-2-dividend-dates" },
    { q: "On the ex-dividend date, a stock's price typically:",
      options: ["Rises by the dividend amount", "Is unaffected", "Stops trading for one day", "Falls by about the dividend amount"], answer: 3,
      explain: "New buyers no longer get the dividend, so the stock opens lower by about the dividend amount.",
      section: "s1-2-dividend-dates" },
    { q: "An investor owns 300 shares at $80. After a 2-for-1 split, the investor has:",
      options: ["300 shares at $40", "600 shares at $40", "600 shares at $80", "150 shares at $160"], answer: 1,
      explain: "Shares double to 600 and the price halves to $40. Total value stays $24,000.",
      section: "s1-2-splits" },
    { q: "An investor owns 1,000 shares at $2. After a 1-for-5 reverse split, the investor has:",
      options: ["5,000 shares at $0.40", "200 shares at $10", "200 shares at $2", "1,000 shares at $10"], answer: 1,
      explain: "1,000 ÷ 5 = 200 shares; $2 × 5 = $10. Total value stays $2,000.",
      section: "s1-2-splits" },
    { q: "Compared with warrants, subscription rights are:",
      options: ["Long term with an exercise price above market", "Short term with an exercise price below market", "Long term with an exercise price below market", "Short term with an exercise price above market"], answer: 1,
      explain: "Rights last 30–45 days and let existing holders buy below market. Warrants last years and are priced above market at issuance.",
      section: "s1-2-rights-warrants" },
    { q: "Warrants are most often attached to a new bond issue in order to:",
      options: ["Make the offering more attractive", "Guarantee principal repayment", "Give bondholders voting rights", "Satisfy preemptive rights"], answer: 0,
      explain: "Warrants are a sweetener. Investors accept a lower interest rate in exchange for the chance to buy stock later.",
      section: "s1-2-rights-warrants" },
    { q: "Which risk does a U.S. investor still face when holding an ADR priced in dollars?",
      options: ["Currency risk", "Call risk", "Reinvestment risk only", "No additional risk"], answer: 0,
      explain: "The underlying shares and dividends are in a foreign currency. If that currency weakens against the dollar, the ADR's value and dividends fall.",
      section: "s1-3-adrs" },
    { q: "How is a stock dividend taxed when received?",
      options: ["As ordinary income at fair market value", "As a capital gain", "It is not taxed when received; cost basis per share is adjusted", "At the qualified dividend rate"], answer: 2,
      explain: "The investor owns the same value in more shares. Tax is deferred until the shares are sold, using the reduced per-share basis.",
      section: "s1-2-dividends" },
    { q: "Which type of company is most likely to reinvest its profits instead of paying a dividend?",
      options: ["A mature utility", "A growth company", "A defensive food producer", "A blue-chip bank"], answer: 1,
      explain: "Growth companies put earnings back into the business to expand. Investors expect to profit from a rising share price rather than dividends.",
      section: "s1-1" },
    { q: "Which stock is most likely to hold up best during a recession?",
      options: ["An automaker", "A luxury hotel chain", "An electric utility", "A heavy-equipment maker"], answer: 2,
      explain: "Utilities are defensive: people keep paying for power in a downturn. Autos, hotels and heavy equipment are cyclical.",
      section: "s1-1-types" },
    { q: "Apoapsis Launch Co. sells 2 million new shares to the public in its IPO. This happens in the:",
      options: ["Secondary market, and investors receive the proceeds", "Primary market, and the company receives the proceeds", "Third market, and the underwriter keeps the proceeds", "Secondary market, and the company receives the proceeds"], answer: 1,
      explain: "New issues are sold in the primary market, and the money goes to the issuer. Later trades between investors happen in the secondary market, where the company receives nothing.",
      section: "s1-3-markets" },
    { q: "Which risk can be reduced by holding a diversified portfolio of many stocks?",
      options: ["Market (systematic) risk", "Inflation risk", "Interest rate risk", "Business (unsystematic) risk"], answer: 3,
      explain: "Unsystematic risks are specific to one company or industry, so spreading money across many stocks reduces them. Systematic risks such as market, inflation and interest rate risk hit everything and cannot be diversified away.",
      section: "s1-4-risk" },
    { q: "A company has 50 million shares outstanding trading at $80. Its market capitalization is:",
      options: ["$4 billion, making it a mid-cap", "$400 million, making it a small-cap", "$40 billion, making it a large-cap", "$4 billion, making it a large-cap"], answer: 0,
      explain: "Market cap = price × outstanding shares = $80 × 50,000,000 = $4 billion. That falls in the mid-cap range ($2 billion to $10 billion).",
      section: "s1-4-cap" },
    { q: "On a balance sheet, stockholders' equity equals:",
      options: ["Revenue minus expenses", "Total assets minus total liabilities", "Net income minus dividends", "Current assets minus current liabilities"], answer: 1,
      explain: "Assets − liabilities = stockholders' equity (net worth). Revenue − expenses is from the income statement; net income − dividends adds to retained earnings; current assets − current liabilities is working capital.",
      section: "s1-5-balance" },
    { q: "A stock trades at $60 and the company earned $3 per share. What is its P/E ratio?",
      options: ["5", "18", "0.05", "20"], answer: 3,
      explain: "P/E = price ÷ earnings per share = $60 ÷ $3 = 20. Investors are paying $20 for every $1 of annual earnings.",
      section: "s1-5-pe" }
  ]
};
