/* Chapter 3 quiz. Each question: q, options (4), answer (0-3), explain, section (textbook anchor id). */
window.QUIZ = {
  chapter: "ch3",
  title: "Chapter 3: Bonds",
  textbook: "textbook.html",
  questions: [
    { q: "A bondholder is best described as:",
      options: ["An owner of the issuing company", "A lender to the issuer", "A partner who shares in the profits", "A voting shareholder"], answer: 1,
      explain: "Buying a bond means lending money. The issuer owes the bondholder interest and the return of principal, but the bondholder owns no part of the company.",
      section: "s3-1-basics" },
    { q: "Unless a question says otherwise, what par value should you assume for a bond?",
      options: ["$10", "$100", "$500", "$1,000"], answer: 3,
      explain: "Bonds are assumed to have a $1,000 par value. Preferred stock is the one that uses $100.",
      section: "s3-1-basics" },
    { q: "The legal contract that sets out a bond's terms, such as its coupon rate and maturity date, is called the:",
      options: ["Indenture", "Prospectus", "Trade confirmation", "Underwriting agreement"], answer: 0,
      explain: "The indenture (also called the trust indenture or deed of trust) is the contract between the issuer and the bondholders. A trustee makes sure the issuer keeps its promises.",
      section: "s3-1-basics" },
    { q: "A 6% corporate bond has a $1,000 par value. How much interest does it pay at each semiannual payment?",
      options: ["$6", "$15", "$60", "$30"], answer: 3,
      explain: "Annual interest is 6% × $1,000 = $60, always figured from par. Corporate bonds pay twice a year, so each payment is $60 ÷ 2 = $30.",
      section: "s3-1-interest" },
    { q: "A 5% bond ($1,000 par) is trading at 80. What is its current yield?",
      options: ["4.00%", "5.00%", "6.25%", "8.00%"], answer: 2,
      explain: "Current yield = annual interest ÷ market price = $50 ÷ $800 = 6.25%. Buying below par pushes the yield above the coupon rate.",
      section: "s3-1-interest" },
    { q: "A bond quoted at 102 is priced at:",
      options: ["$102", "$1,020", "$10.20", "$1,002"], answer: 1,
      explain: "Bond prices are quoted as a percent of par. 102% of $1,000 is $1,020, so each point is worth $10.",
      section: "s3-2-price" },
    { q: "A bond trading above par is said to trade at a ______, and its current yield is ______ its coupon rate.",
      options: ["Premium; below", "Premium; above", "Discount; below", "Discount; above"], answer: 0,
      explain: "Above par is a premium. The same fixed interest divided by a higher price gives a lower yield, so current yield falls below the coupon rate.",
      section: "s3-2-price" },
    { q: "If market interest rates rise, the prices of existing bonds will most likely:",
      options: ["Rise", "Stay at par", "Fall", "Rise if the bond is callable"], answer: 2,
      explain: "Existing bonds pay a fixed coupon. When new bonds pay more, buyers want a discount on the old ones, so their prices fall. Rates and bond prices move in opposite directions.",
      section: "s3-2-rates" },
    { q: "Which of these bonds will change most in price when interest rates change?",
      options: ["A 2-year bond with a 6% coupon", "A 30-year bond with a 3% coupon", "A 10-year bond with a 6% coupon", "A 5-year bond with a 4% coupon"], answer: 1,
      explain: "The longer the maturity and the lower the coupon, the more the price reacts to a change in rates. A 30-year, 3% bond is the most sensitive of these.",
      section: "s3-2-rates" },
    { q: "For a bond trading at a discount, which list ranks its yields from highest to lowest?",
      options: ["Yield to maturity, current yield, coupon rate", "Coupon rate, current yield, yield to maturity", "Current yield, coupon rate, yield to maturity", "Coupon rate, yield to maturity, current yield"], answer: 0,
      explain: "At a discount, the buyer earns the coupon plus a gain as the price rises to par. Yield to maturity counts that gain, so the order is yield to maturity, then current yield, then coupon rate. At a premium the order reverses.",
      section: "s3-2-ytm" },
    { q: "Which issuer's bonds are backed by the full faith and credit of the U.S. government?",
      options: ["Corporations", "Municipalities", "Treasury", "Foreign governments"], answer: 2,
      explain: "U.S. Treasury securities carry the government's full faith and credit, so they have the lowest credit risk. Corporate and municipal bonds depend on the issuer's own ability to pay.",
      section: "s3-3-issuers" },
    { q: "The interest from U.S. Treasury securities is generally:",
      options: ["Taxed by the federal government but not by state or local governments", "Taxed by federal, state and local governments", "Exempt from federal tax but taxed by states", "Exempt from all income taxes"], answer: 0,
      explain: "Treasury interest is subject to federal income tax but exempt from state and local income taxes.",
      section: "s3-3-issuers" },
    { q: "The interest from most municipal bonds is generally exempt from:",
      options: ["Sales tax", "Social Security tax", "Estate tax", "Federal income tax"], answer: 3,
      explain: "Interest on most municipal bonds is exempt from federal income tax, which is why these bonds can pay lower rates than similar taxable bonds.",
      section: "s3-3-issuers" },
    { q: "What is the lowest investment-grade rating from Standard & Poor's?",
      options: ["BB", "BBB", "A", "B"], answer: 1,
      explain: "S&P's investment-grade ratings run from AAA down to BBB. Anything rated BB or lower is high yield. Moody's equivalent is Baa.",
      section: "s3-3-ratings" },
    { q: "A bond rated BB by Standard & Poor's is best described as:",
      options: ["Investment grade", "High yield (speculative)", "Backed by the Treasury", "Certain never to default"], answer: 1,
      explain: "BB is below the BBB line, so it is a high-yield (speculative, or junk) bond. Investors demand a higher yield because default is more likely.",
      section: "s3-3-ratings" },
    { q: "An investor holds a bond that the issuer calls after interest rates have fallen. The investor now faces mainly:",
      options: ["Credit risk", "Liquidity risk", "Inflation risk", "Reinvestment risk"], answer: 3,
      explain: "The investor gets the call price back just when rates are low, so the money can only be reinvested at lower rates.",
      section: "s3-4-risks" },
    { q: "The risk that an issuer fails to make its interest or principal payments is called:",
      options: ["Interest rate risk", "Call risk", "Credit (default) risk", "Purchasing power risk"], answer: 2,
      explain: "Credit risk, also called default risk, is the chance the issuer can't pay. Ratings from Moody's, S&P and Fitch help measure it.",
      section: "s3-4-risks" },
    { q: "Rising inflation hurts a bondholder mainly because:",
      options: ["The coupon rate is cut", "Par value is reduced", "The bond is automatically called", "The fixed interest and the returned principal buy less"], answer: 3,
      explain: "Interest payments and principal are fixed in dollars, so their purchasing power shrinks as prices rise. Rising inflation also tends to push rates up and bond prices down.",
      section: "s3-4-risks" },
    { q: "In a corporate liquidation, which group is paid first?",
      options: ["Common stockholders", "Preferred stockholders", "Bondholders", "All groups are paid at the same time"], answer: 2,
      explain: "Bondholders are creditors. Creditors are paid before any stockholders, and preferred stockholders are paid before common stockholders.",
      section: "s3-4-vs" },
    { q: "Compared with common stockholders, bondholders usually:",
      options: ["Receive interest that is legally owed, and have no vote", "Have voting rights, but no right to interest", "Share in profits and have no maturity date", "Own a piece of the company"], answer: 0,
      explain: "Bondholders are creditors. Their interest and principal are legal obligations and they have a maturity date, but they don't vote and don't share in company growth.",
      section: "s3-4-vs" }
  ]
};
