/* Chapter 2 quiz. Each question: q, options (4), answer (0-3), explain, section (textbook anchor id). */
window.QUIZ = {
  chapter: "ch2",
  title: "Chapter 2: Preferred Stock",
  textbook: "textbook.html",
  questions: [
    { q: "Unless a question says otherwise, what par value should you assume for preferred stock?",
      options: ["$1", "$10", "$100", "$1,000"], answer: 2,
      explain: "Preferred stock is assumed to have a $100 par value. Its dividend is figured as a percentage of that par.",
      section: "s2-1-dividends" },
    { q: "An investor buys a 6% preferred stock at $120 a share. What annual dividend does the investor receive per share?",
      options: ["$6.00", "$7.20", "$5.00", "$12.00"], answer: 0,
      explain: "The dividend is always figured from par, not the market price: 6% × $100 = $6. The $120 price affects the yield, not the dividend.",
      section: "s2-1-dividends" },
    { q: "A 5% preferred stock is trading at $80. Its current yield is:",
      options: ["4.00%", "5.00%", "5.80%", "6.25%"], answer: 3,
      explain: "Current yield = annual dividend ÷ market price = $5 ÷ $80 = 6.25%. Buying below par pushes the yield above the dividend rate.",
      section: "s2-1-yield" },
    { q: "A preferred stock trading above its par value has a current yield that is:",
      options: ["Higher than its dividend rate", "Lower than its dividend rate", "Equal to its dividend rate", "Zero until the price returns to par"], answer: 1,
      explain: "Price and yield move in opposite directions. At a premium, the same fixed dividend divided by a higher price gives a yield below the dividend rate.",
      section: "s2-1-yield" },
    { q: "If market interest rates rise, the price of an existing preferred stock will most likely:",
      options: ["Fall", "Rise", "Stay at par", "Rise by the amount of one dividend"], answer: 0,
      explain: "Preferred stock competes with other fixed-income investments. When new investments pay more, existing preferred stock's price falls until its yield is competitive again.",
      section: "s2-1-rates" },
    { q: "Compared with common stockholders, preferred stockholders usually:",
      options: ["Have more votes per share", "Receive dividends first but have no voting rights", "Are paid before creditors in a liquidation", "Receive a dividend that grows with earnings"], answer: 1,
      explain: "Preferred comes ahead of common for dividends and in liquidation, but it usually carries no vote and its dividend is fixed. Creditors are still paid before preferred.",
      section: "s2-1" },
    { q: "A company has $100 par, 5% cumulative preferred. It skipped the dividend for two years, paid 3% last year, and now wants to pay a common dividend. How much per preferred share must it pay first?",
      options: ["$5", "$12", "$15", "$17"], answer: 3,
      explain: "Cumulative preferred must be paid all arrears plus the current dividend: $5 + $5 + $2 (the shortfall last year) + $5 this year = $17.",
      section: "s2-2-cumulative" },
    { q: "With straight (non-cumulative) preferred stock, a dividend the board skips is:",
      options: ["Paid later with interest", "Added to the par value", "Lost for good", "Converted into common stock"], answer: 2,
      explain: "Straight preferred has no right to missed dividends. Only the current year's preferred dividend must be paid before common stockholders get anything.",
      section: "s2-2-cumulative" },
    { q: "Participating preferred stock allows the holder to:",
      options: ["Vote for the board of directors", "Receive more than the stated dividend in profitable years", "Exchange the shares for bonds", "Force the company to buy back the shares"], answer: 1,
      explain: "Participating preferred shares in extra profits: a 5% participating issue might pay more than 5% in a strong year.",
      section: "s2-2-participating" },
    { q: "An issuer is most likely to call its preferred stock when:",
      options: ["Interest rates have fallen", "Interest rates have risen", "Its common stock price has fallen", "It has just skipped a dividend"], answer: 0,
      explain: "When rates fall, the issuer can sell new preferred at a lower dividend rate and use the money to call the old, higher-paying shares.",
      section: "s2-2-callable" },
    { q: "A $100 par preferred stock is \"callable at 103 after 5 years.\" What are the call premium and the call protection?",
      options: ["$3 premium; 5 years of protection", "$103 premium; 5 years of protection", "$3 premium; 103 days of protection", "$5 premium; 3 years of protection"], answer: 0,
      explain: "Callable at 103 means $103 for a $100 par share, a $3 premium. The issuer can't call during the first 5 years: that is the call protection.",
      section: "s2-2-callable" },
    { q: "A convertible preferred stock has a conversion ratio of 4:1, and the common stock trades at $28. What is the conversion value?",
      options: ["$25", "$28", "$112", "$32"], answer: 2,
      explain: "Conversion value = conversion ratio × common price = 4 × $28 = $112.",
      section: "s2-2-convertible" },
    { q: "An investor buys 100 shares of convertible preferred at $95. Each share converts into 4 common shares. The common rises to $30, and the investor converts and sells. What is the gain?",
      options: ["$500", "$2,500", "$3,000", "$12,000"], answer: 1,
      explain: "Cost: 100 × $95 = $9,500. Conversion gives 400 common shares, sold at $30 for $12,000. Gain: $12,000 − $9,500 = $2,500.",
      section: "s2-2-convertible" },
    { q: "Which preferred stock feature benefits the issuer rather than the investor?",
      options: ["Cumulative", "Participating", "Convertible", "Callable"], answer: 3,
      explain: "A call lets the issuer take the shares back, usually when rates are low. Cumulative, participating and convertible features all benefit the investor.",
      section: "s2-2-effects" },
    { q: "Compared with a similar straight preferred, a cumulative preferred will typically have:",
      options: ["A higher price and a lower yield", "A lower price and a higher yield", "The same price and yield", "A higher dividend rate and a higher yield"], answer: 0,
      explain: "Investors pay more for features that protect them. A higher price for the same dividend means a lower yield, so the issuer can offer a lower dividend rate.",
      section: "s2-2-effects" },
    { q: "Why does preferred stock usually yield more than bonds issued by the same company?",
      options: ["Preferred dividends are guaranteed by law", "Preferred stock has a maturity date", "Preferred dividends are not a legal obligation, so investors take more risk", "Preferred stockholders are paid before bondholders in a liquidation"], answer: 2,
      explain: "Bond interest is a legal obligation; preferred dividends can be skipped. Investors demand a higher yield for that extra risk.",
      section: "s2-3-benefits" },
    { q: "In a corporate liquidation, preferred stockholders are paid:",
      options: ["Before secured creditors", "After all creditors but before common stockholders", "After common stockholders", "At the same time as bondholders"], answer: 1,
      explain: "The order is unpaid wages, unpaid taxes, secured creditors, unsecured creditors, junior unsecured creditors, then preferred stockholders, and common stockholders last.",
      section: "s2-3-risks" },
    { q: "Rising inflation hurts a preferred stockholder mainly because:",
      options: ["The board must cut the dividend rate", "Par value falls with inflation", "The shares are automatically converted", "The fixed dividend buys less"], answer: 3,
      explain: "The dividend is fixed, so its purchasing power shrinks as prices rise. High inflation also tends to push preferred prices down.",
      section: "s2-3-risks" },
    { q: "A preferred stock is called after interest rates fall. The investor now faces mainly:",
      options: ["Reinvestment risk", "Liquidity risk", "Currency risk", "Legislative risk"], answer: 0,
      explain: "The investor gets the call price back just when rates are low, so the money can only be reinvested at lower rates.",
      section: "s2-3-risks" },
    { q: "Preferred stock is most suitable for an investor who:",
      options: ["Wants maximum growth over the next year", "Needs steady income and has a long time horizon", "Plans to sell within a few months", "Wants a vote on the board of directors"], answer: 1,
      explain: "Preferred stock suits income-focused, fairly conservative investors with a long time horizon. It has no maturity date, and short-term holders risk selling after rates rise.",
      section: "s2-3-investor" }
  ]
};
